type Query {
	"Obtenemos las lista de todos los usuarios"
	users: [User!]!
	"Iniciamos sesión en el sistema"
	login(cor: String!, pwd: String!): ResultTk!
	"Obtener nuestra información con el tk"
	me: User!
}

type Mutation {
	"Registro de los usuarios en el sistema"
	register(user: UserInput): User!
}

type User {
	id: ID!
	nom: String!
	ape: String!
	cor: String!
	pwd: String!
	createdAt: String!
}

input UserInput {
	nom: String!
	ape: String!
	cor: String!
	pwd: String!
}

type ResultTk {
	tk: String!
}
